export const PROFESSIONAL_TRIALS = {
  count: "15+",
  sports: [
    "Premiership Rugby",
    "Pro 14 Rugby",
    "GB Sevens (Men)",
    "GB Sevens (Women)",
    "Premier League",
    "EFL Championship",
    "Bundesliga",
    "NFL",
    "Boxing",
    "UCI Cycling",
    "University Sport",
  ],
  orgs: [
    "Harlequins",
    "Bristol Bears",
    "Sale Sharks",
    "Stade Toulouse",
    "GB 7s Men",
    "GB 7s Women",
    "Leeds FC",
    "Blackburn Rovers",
    "Bayern Munich",
    "LA Rams",
    "Orbea FMD Racing",
    "Adam Azim",
    "CBS Boxing",
    "Oxford University Rugby",
    "Loughborough Rugby",
  ],
  note: "All club data is held privately under NDA.",
} as const;
